---
all:
  vars:
    # Control host for running plays locally
    ansible_connection: local
    ansible_python_interpreter: "{{ ansible_playbook_python }}"

  hosts:
    localhost:
      ansible_connection: local

  children:
    proxmox_control:
      hosts:
        localhost:
